'use client'
import { useCallback,useEffect,useState,type FormEvent } from 'react'
import { Plus,Trash,PencilSimple } from '@phosphor-icons/react'
import { useAuth } from '@/components/auth-provider'
import { supabase } from '@/lib/supabase'
import { localDate,niceDate } from '@/lib/utils'
import { errorMessage,type JournalEntry } from '@/lib/data'
export default function Journal(){
  const {user}=useAuth();const [entries,setEntries]=useState<JournalEntry[]>([]);const [editing,setEditing]=useState<string|null>(null);const [date,setDate]=useState(localDate());const [title,setTitle]=useState('');const [content,setContent]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const load=useCallback(async()=>{const {data,error}=await supabase().from('journal_entries').select('id,entry_date,title,content,created_at').order('entry_date',{ascending:false}).limit(100);if(error)setError(error.message);else setEntries(data??[])},[])
  useEffect(()=>{if(user)queueMicrotask(()=>{void load()})},[user,load])
  async function save(e:FormEvent){e.preventDefault();if(!user)return;setBusy(true);setError('');try{const client=supabase();const payload={entry_date:date,title:title.trim()||null,content:content.trim()};const {error}=editing?await client.from('journal_entries').update(payload).eq('id',editing):await client.from('journal_entries').insert({...payload,user_id:user.id});if(error)throw error;setEditing(null);setDate(localDate());setTitle('');setContent('');await load()}catch(caught){setError(errorMessage(caught))}finally{setBusy(false)}}
  function edit(entry:JournalEntry){setEditing(entry.id);setDate(entry.entry_date);setTitle(entry.title??'');setContent(entry.content);window.scrollTo({top:0,behavior:'smooth'})}
  async function remove(id:string){if(!window.confirm('Delete this note?'))return;const {error}=await supabase().from('journal_entries').delete().eq('id',id);if(error)setError(error.message);else await load()}
  return <><div className="page-head"><div className="eyebrow">The details matter</div><h1>Journal.</h1><p>Write down what the numbers do not capture.</p></div>{error&&<div className="notice" role="alert" style={{marginBottom:16}}>{error}</div>}<form className="card stack" onSubmit={save}><h2>{editing?'Edit note':'New note'}</h2><div className="field-row"><div><label htmlFor="note-date">Date</label><input id="note-date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div><label htmlFor="note-title">Title (optional)</label><input id="note-title" maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Training, diet, recovery…"/></div></div><div><label htmlFor="note-content">What happened?</label><textarea id="note-content" required value={content} onChange={e=>setContent(e.target.value)} placeholder="What felt strong? What will you change next time?"/></div><div className="row" style={{justifyContent:'flex-start'}}><button className="btn primary" disabled={busy||!content.trim()}><Plus size={17}/>{editing?'Save changes':'Save note'}</button>{editing&&<button type="button" className="btn ghost" onClick={()=>{setEditing(null);setTitle('');setContent('')}}>Cancel edit</button>}</div></form><div className="section-head"><h2>Past notes</h2></div>{entries.length===0?<div className="empty">Your notes will live here.</div>:<div className="stack">{entries.map(entry=><article className="card" key={entry.id}><div className="row"><div className="eyebrow">{niceDate(entry.entry_date)}</div><div className="row"><button className="btn ghost small" aria-label="Edit note" onClick={()=>edit(entry)}><PencilSimple size={17}/></button><button className="btn ghost small danger" aria-label="Delete note" onClick={()=>remove(entry.id)}><Trash size={17}/></button></div></div>{entry.title&&<h2 style={{marginTop:12}}>{entry.title}</h2>}<p style={{whiteSpace:'pre-wrap',marginBottom:0}}>{entry.content}</p></article>)}</div>}</>
}
