'use client'
import { useCallback,useEffect,useState,type FormEvent } from 'react'
import Link from 'next/link'
import { ArrowLeft,Plus,Check,Trash } from '@phosphor-icons/react'
import { useAuth } from '@/components/auth-provider'
import { supabase } from '@/lib/supabase'
import { localDate,niceDate } from '@/lib/utils'
import { errorMessage } from '@/lib/data'
type Goal={id:string;name:string;description:string|null;start_date:string|null;target_date:string|null;active:boolean}
export default function Goals(){
  const {user}=useAuth();const [goals,setGoals]=useState<Goal[]>([]);const [name,setName]=useState('');const [description,setDescription]=useState('');const [targetDate,setTargetDate]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const load=useCallback(async()=>{const {data,error}=await supabase().from('goals').select('id,name,description,start_date,target_date,active').order('created_at',{ascending:false});if(error)setError(error.message);else setGoals(data??[])},[])
  useEffect(()=>{if(user)queueMicrotask(()=>{void load()})},[user,load])
  async function add(e:FormEvent){e.preventDefault();if(!user)return;setBusy(true);setError('');try{const {error}=await supabase().from('goals').insert({user_id:user.id,name:name.trim(),description:description.trim()||null,start_date:localDate(),target_date:targetDate||null});if(error)throw error;setName('');setDescription('');setTargetDate('');await load()}catch(caught){setError(errorMessage(caught))}finally{setBusy(false)}}
  async function toggle(goal:Goal){const {error}=await supabase().from('goals').update({active:!goal.active}).eq('id',goal.id);if(error)setError(error.message);else await load()}
  async function remove(id:string){if(!window.confirm('Delete this goal?'))return;const {error}=await supabase().from('goals').delete().eq('id',id);if(error)setError(error.message);else await load()}
  return <><Link href="/settings" className="muted small row" style={{justifyContent:'flex-start',marginBottom:16}}><ArrowLeft size={16}/> Settings</Link><div className="page-head"><div className="eyebrow">What you are working toward</div><h1>Goals.</h1><p>Keep your current target visible and concrete.</p></div>{error&&<div className="notice" role="alert" style={{marginBottom:14}}>{error}</div>}<form className="card stack" onSubmit={add}><h2>Add a goal</h2><div><label htmlFor="goal-name">Goal</label><input id="goal-name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Gain 3 kg, increase squat, stay consistent…"/></div><div><label htmlFor="goal-description">Details (optional)</label><textarea id="goal-description" value={description} onChange={e=>setDescription(e.target.value)}/></div><div><label htmlFor="goal-date">Target date (optional)</label><input id="goal-date" type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></div><button className="btn primary" disabled={busy||!name.trim()} style={{justifySelf:'start'}}><Plus size={17}/> Save goal</button></form><div className="section-head"><h2>Your goals</h2></div>{goals.length===0?<div className="empty">A clear target gives the daily work direction.</div>:<div className="stack">{goals.map(goal=><div className="card row wrap" key={goal.id}><div><span className={`pill ${goal.active?'orange':'green'}`}>{goal.active?'Active':'Done'}</span><h3 style={{marginTop:10}}>{goal.name}</h3>{goal.description&&<p className="muted small">{goal.description}</p>}{goal.target_date&&<div className="muted small">Target: {niceDate(goal.target_date)}</div>}</div><div className="row"><button className="btn small" onClick={()=>toggle(goal)}><Check size={16}/>{goal.active?'Mark done':'Reopen'}</button><button className="btn ghost small danger" aria-label="Delete goal" onClick={()=>remove(goal.id)}><Trash size={16}/></button></div></div>)}</div>}</>
}
